name: build
on:
  workflow_dispatch:
#  pull_request:
  push:
#    branches:
#      - master
    tags:
      - "v*"
jobs:
  desktop:
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Build Target
        run: gradle packageReleaseDistributionForCurrentOS
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: cm-bs-helper-${{ runner.os }}
          path: |
            desktopApp/build/compose/binaries/main-release/msi/*.msi
            desktopApp/build/compose/binaries/main-release/exe/*.exe
#            desktopApp/build/compose/binaries/main-release/deb/*.deb
#            desktopApp/build/compose/binaries/main-release/dmg/*.dmg
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "desktopApp/build/compose/binaries/main-release/msi/*.msi,desktopApp/build/compose/binaries/main-release/deb/*.deb,desktopApp/build/compose/binaries/main-release/dmg/*.dmg,desktopApp/build/compose/binaries/main-release/exe/*.exe"

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: remove unsigned APK
        id: remove-unsigned-apk
        run: find androidApp/build/outputs/apk/debug/ -type f -name '*.apk' ! -name '*-signed.apk' -delete
      - name: rename APK
        id: rename-signed-apk
        run: for file in androidApp/build/outputs/apk/debug/*-signed.apk; do mv "$file" "${file%-signed.apk}.apk"; done
      - name: Upload Build APK
        uses: actions/upload-artifact@v3
        with:
          name: cm-bs-helper-android
          path: |
            androidApp/build/outputs/apk/debug/*.apk
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "androidApp/build/outputs/apk/debug/*.apk"
