name: build
on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#      - master

jobs:
  desktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Build Target
        run: gradle packageReleaseDistributionForCurrentOS

      - name: set env for different OS
      - run: if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then export EXT='deb'; fi
      - run: if [ ${{ matrix.os }} == 'macos-latest' ]; then export EXT='dmg'; fi
      - run: if [ ${{ matrix.os }} == 'windows-latest' ]; then export EXT='exe'; fi
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: desktop/build/compose/binaries/main/${{env.EXT}}/CM-BS-Helper-0.0.1-test.${{env.EXT}}
      - name: Build APK
        if: runner.os == 'Linux'
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload Build APK
        uses: actions/upload-artifact@v3
        with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk