name: build
on:
  workflow_dispatch:
#  pull_request:
  push:
#    branches:
#      - master
    tags:
      - "v*"
jobs:
  desktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
      - name: Build Target
        run: gradle packageReleaseDistributionForCurrentOS
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: executable
#          todo retrieve version and packagename from gradle
          path: |
            desktop/build/compose/binaries/main*/[msi|dmg|deb]/*.[msi|dmg|deb]
      - name: Build APK
        if: runner.os == 'Linux'
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload Build APK
        uses: actions/upload-artifact@v3
        with:
         name: cm-bs-helper
         path: android/build/outputs/apk/debug/android-debug.apk
